---
title: PACKAGE REVIEW
author: chenjie gong 
date: '2020-10-24'
slug: peer reviewing package
categories: []
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: '2020-10-24T20:38:11+08:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---
# Overview
In this blog post I will be reviewing alangewerc's R package `covidshiny` which is containing coronavirus data, functions, and shiny application. The development version from [GitHub](https://github.com/etc5523-2020/r-package-assessment-alangewerc).

The goal of CovidShiny is to present the user the evolution of the pandemic related to COVID-19 across the world. This is accomplished by a range of visualizations such as dot density map, table and stacked plots. This visualizations are presented in a Shiny web app.

##  What did I think this package would do? Did it do it?

I am going to break this question up into four subsections to consider.

#### The Datasets

When I entered `covidshiny::coviddata`and `covidshiny::preprocessedcoviddata` into the console they did exactly what I thought they would do. They presented the relevant data frames, which were then called upon in the app. 
   
#### The Launch App Function

The `covidshiny::launch_app()` launched the application, as expected. This function was particularly useful , because it can help people quickly access this application.

#### The column_plotly function

The `column_plotly` function  generated a column in a fluidrow with a plotly inside.

When I entered the example code into the console it can generated it 
`(<div class="col-sm-3"><div id="plotlytotalcases" style="width:100%; height:300px; "class="plotly html-widget html-widget-output shiny-report-size"></div>)`
I get this output, I think it's work in the shiny app, because this function only check n_char and n_input, and set column(3), height= '300px'.
  so it work, well job :D


#### The plot_cases function   

The `plot_cases` function his function gives the user a stacked barchart plotly after performing dplyr::filtering in the dataset CovidData.

This function relies on the user input. Using this function, the application generates  plots displaying the deaths per-million. 

When I entered the `covidshiny::plot_cases` in the console, it can generated it(<shiny.render.function> ), so yes I think this function is work.

## Improvements

#### The Code

I think the code is well-written, however,  it cannot pass the R-CMD check.
I just use devtool::check() in local , I find the problem in the vignette file.
so I recommend you re-building ‘shinyCovid.Rmd’ to find the error.
The second problem is your set duplicate chunk label 'setup'.


#### The Shiny Application

The app This shiny application allows user to visualise different variables regarding cases and deaths of Covid-19 across the world. Multiple tools are used such as Map, table and plots.  


I think the only improvement that in the second part ,you can fecat the figure only 2 or 3 nrow,because it can more clearly show the information. 

#### The Documentation

The goal of CovidShiny is to present the user the evolution of the pandemic related to COVID-19 across the world. This is accomplished by a range of visualizations such as dot density map, table and stacked plots. This visualizations are presented in a Shiny web app.

The user may interact with the data in a variety of forms, using sliders, action buttons and input boxes that will define what variables will presented in each visualization.

We create a processed dataset that can be accessed with function covidData. It is the same dataset but in a tidy format. The user can access the pre processed data with `preProcessedCovidData".

This package has also improved the previous Shiny application by creating new functions that improve the logic of the application, reducing the number of line of codes in the Ui and Server functions.

Finally, diverse tests were put in place to make sure functions are working properly. To know more about this package access the following website.

The documentation in the README file is very detailed and provides a great overview of the package and the application.  good job! 

I think the only improvement that you need show the data's variable ,obeserve and 
citation.
 
## I learn from this review

1.I learn a lot in reviewing the shiny app, I think put the UI and SERVER in different file is good to people read.
2.use the cols_align() function in the UI
3.In the file using `######`as a dividing line to show the functions of different partitions.
just like this:
`#####################################`
 `## Table - using GT`
`#####################################`

## Appendix


## Package Review
This package is embedding a Shiny application dashboard about COVID-19. It was developed for an assessment of the unit “ETC5523 - Communicating with Data” of the Master of Business Analytics at Monash University.

#### Documentation

The package includes all the following forms of documentation:

- [ ] **A statement of need** clearly stating problems the software is designed to solve and its target audience in README
- [ ] **Installation instructions:** for the development version of package and any non-standard dependencies in README
- [ ] **Function Documentation:** for all exported functions in R help
- [ ] **Examples** for all exported functions in R Help that run successfully locally


#### Functionality

- [ ] **Installation:** Installation succeeds as documented.
- [ ] **Functionality:** Any functional claims of the software been confirmed.
- [ ] **Performance:** Any performance claims of the software been confirmed.


### Review Comments
 
I think you did excellent job :P






